/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthenticationStatusResponseSchemasType - The type of the event.
 */
public enum AuthenticationStatusResponseSchemasType {
    ATTEMPT("attempt"),
    CHECK("check"),
    DELIVERY_STATUS("delivery_status"),
    BALANCE_UPDATE("balance_update");

    @JsonValue
    private final String value;

    private AuthenticationStatusResponseSchemasType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthenticationStatusResponseSchemasType> fromValue(String value) {
        for (AuthenticationStatusResponseSchemasType o: AuthenticationStatusResponseSchemasType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
