/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * AuthenticationStatusResponseSchemasStatus - The status of the attempt. Possible values are:
 *   * `pending` - The attempt is pending.
 *   * `delivered` - The attempt was delivered.
 *   * `failed` - The attempt failed.
 *   * `rate_limited` - The authentication was rate limited and cannot be retried.
 *   * `expired` - The authentication has expired and cannot be retried.
 * 
 */
public enum AuthenticationStatusResponseSchemasStatus {
    PENDING("pending"),
    DELIVERED("delivered"),
    FAILED("failed"),
    RATE_LIMITED("rate_limited"),
    EXPIRED("expired");

    @JsonValue
    private final String value;

    private AuthenticationStatusResponseSchemasStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
