/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthenticationStatusResponseDeviceType - The type of device the user is using.
 */
public enum AuthenticationStatusResponseDeviceType {
    ANDROID("ANDROID"),
    IOS("IOS"),
    IPADOS("IPADOS"),
    TVOS("TVOS"),
    WEB("WEB");

    @JsonValue
    private final String value;

    private AuthenticationStatusResponseDeviceType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthenticationStatusResponseDeviceType> fromValue(String value) {
        for (AuthenticationStatusResponseDeviceType o: AuthenticationStatusResponseDeviceType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
