/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * AuthenticationStatusResponseDeviceType - The type of device the user is using.
 */
public enum AuthenticationStatusResponseDeviceType {
    IOS("IOS"),
    ANDROID("ANDROID"),
    WEB("WEB");

    @JsonValue
    private final String value;

    private AuthenticationStatusResponseDeviceType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
