/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * AuthenticationStatusResponseStatus - The status of the delivery. Possible values are:
 *   * `unknown` - The status of the delivery is unknown.
 *   * `submitted` - The message has been submitted to the carrier.
 *   * `in_transit` - The message is in transit to the recipient.
 *   * `delivered` - The message has been delivered to the recipient.
 *   * `undeliverable` - The message could not be delivered to the recipient.
 * 
 */
public enum AuthenticationStatusResponseStatus {
    UNKNOWN("unknown"),
    SUBMITTED("submitted"),
    IN_TRANSIT("in_transit"),
    DELIVERED("delivered"),
    UNDELIVERABLE("undeliverable");

    @JsonValue
    private final String value;

    private AuthenticationStatusResponseStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
