/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum BalanceUpdateType {
    UNKNOWN("unknown"),
    AUTHENTICATION("authentication"),
    ATTEMPT("attempt"),
    ATTEMPT_PENDING("attempt_pending"),
    ATTEMPT_SUCCESS("attempt_success"),
    AUTHENTICATION_PENDING("authentication_pending"),
    AUTHENTICATION_SUCCESS("authentication_success");

    @JsonValue
    private final String value;

    private BalanceUpdateType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<BalanceUpdateType> fromValue(String value) {
        for (BalanceUpdateType o: BalanceUpdateType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
