/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;
import live.ding.dingSdk.utils.Utils;


public class CreateCheckResponse {

    /**
     * The UUID of the corresponding authentication.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authentication_uuid")
    private Optional<String> authenticationUuid;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private Optional<? extends CheckStatus> status;

    @JsonCreator
    public CreateCheckResponse(
            @JsonProperty("authentication_uuid") Optional<String> authenticationUuid,
            @JsonProperty("status") Optional<? extends CheckStatus> status) {
        Utils.checkNotNull(authenticationUuid, "authenticationUuid");
        Utils.checkNotNull(status, "status");
        this.authenticationUuid = authenticationUuid;
        this.status = status;
    }
    
    public CreateCheckResponse() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * The UUID of the corresponding authentication.
     */
    @JsonIgnore
    public Optional<String> authenticationUuid() {
        return authenticationUuid;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CheckStatus> status() {
        return (Optional<CheckStatus>) status;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The UUID of the corresponding authentication.
     */
    public CreateCheckResponse withAuthenticationUuid(String authenticationUuid) {
        Utils.checkNotNull(authenticationUuid, "authenticationUuid");
        this.authenticationUuid = Optional.ofNullable(authenticationUuid);
        return this;
    }

    /**
     * The UUID of the corresponding authentication.
     */
    public CreateCheckResponse withAuthenticationUuid(Optional<String> authenticationUuid) {
        Utils.checkNotNull(authenticationUuid, "authenticationUuid");
        this.authenticationUuid = authenticationUuid;
        return this;
    }

    public CreateCheckResponse withStatus(CheckStatus status) {
        Utils.checkNotNull(status, "status");
        this.status = Optional.ofNullable(status);
        return this;
    }

    public CreateCheckResponse withStatus(Optional<? extends CheckStatus> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateCheckResponse other = (CreateCheckResponse) o;
        return 
            Objects.deepEquals(this.authenticationUuid, other.authenticationUuid) &&
            Objects.deepEquals(this.status, other.status);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            authenticationUuid,
            status);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateCheckResponse.class,
                "authenticationUuid", authenticationUuid,
                "status", status);
    }
    
    public final static class Builder {
 
        private Optional<String> authenticationUuid = Optional.empty();
 
        private Optional<? extends CheckStatus> status = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The UUID of the corresponding authentication.
         */
        public Builder authenticationUuid(String authenticationUuid) {
            Utils.checkNotNull(authenticationUuid, "authenticationUuid");
            this.authenticationUuid = Optional.ofNullable(authenticationUuid);
            return this;
        }

        /**
         * The UUID of the corresponding authentication.
         */
        public Builder authenticationUuid(Optional<String> authenticationUuid) {
            Utils.checkNotNull(authenticationUuid, "authenticationUuid");
            this.authenticationUuid = authenticationUuid;
            return this;
        }

        public Builder status(CheckStatus status) {
            Utils.checkNotNull(status, "status");
            this.status = Optional.ofNullable(status);
            return this;
        }

        public Builder status(Optional<? extends CheckStatus> status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }
        
        public CreateCheckResponse build() {
            return new CreateCheckResponse(
                authenticationUuid,
                status);
        }
    }
}

