/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package live.ding.dingsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * DeviceType
 * 
 * <p>The type of device the user is using.
 */
public enum DeviceType {
    IOS("IOS"),
    ANDROID("ANDROID"),
    WEB("WEB");

    @JsonValue
    private final String value;

    private DeviceType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<DeviceType> fromValue(String value) {
        for (DeviceType o: DeviceType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

