/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * FeedbackRequestStatus - The type of the feedback.
 */
public enum FeedbackRequestStatus {
    ONBOARDED("onboarded"),
    NOT_ONBOARDED("not_onboarded");

    @JsonValue
    private final String value;

    private FeedbackRequestStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<FeedbackRequestStatus> fromValue(String value) {
        for (FeedbackRequestStatus o: FeedbackRequestStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
