/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import live.ding.dingsdk.utils.SpeakeasyMetadata;
import live.ding.dingsdk.utils.Utils;


public class Security {

    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=x-api-key")
    private String apiKey;

    @JsonCreator
    public Security(
            String apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = apiKey;
    }

    @JsonIgnore
    public String apiKey() {
        return apiKey;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public Security withAPIKey(String apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = apiKey;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Security other = (Security) o;
        return 
            Objects.deepEquals(this.apiKey, other.apiKey);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            apiKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Security.class,
                "apiKey", apiKey);
    }
    
    public final static class Builder {
 
        private String apiKey;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder apiKey(String apiKey) {
            Utils.checkNotNull(apiKey, "apiKey");
            this.apiKey = apiKey;
            return this;
        }
        
        public Security build() {
            return new Security(
                apiKey);
        }
    }
}

