/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * Status - The status of the authentication. Possible values are:
 *   * `pending` - The OTP code is being sent.
 *   * `rate_limited` - This user is rate-limited and cannot receive another code.
 *   * `spam_detected` - This attempt is flagged as spam. Go to the dashboard for more details.
 * 
 */
public enum Status {
    PENDING("pending"),
    RATE_LIMITED("rate_limited"),
    SPAM_DETECTED("spam_detected");

    @JsonValue
    private final String value;

    private Status(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
