/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * Type - The type of the event.
 */
public enum Type {
    ATTEMPT("attempt"),
    CHECK("check"),
    DELIVERY_STATUS("delivery_status"),
    BALANCE_UPDATE("balance_update");

    @JsonValue
    private final String value;

    private Type(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
