/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Exception;
import java.lang.String;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;
import live.ding.dingsdk.models.errors.ErrorResponse;
import live.ding.dingsdk.models.errors.SDKError;
import live.ding.dingsdk.models.operations.LookupRequest;
import live.ding.dingsdk.models.operations.LookupRequestBuilder;
import live.ding.dingsdk.models.operations.LookupResponse;
import live.ding.dingsdk.models.operations.SDKMethodInterfaces.*;
import live.ding.dingsdk.models.operations.Type;
import live.ding.dingsdk.utils.HTTPClient;
import live.ding.dingsdk.utils.HTTPRequest;
import live.ding.dingsdk.utils.Hook.AfterErrorContextImpl;
import live.ding.dingsdk.utils.Hook.AfterSuccessContextImpl;
import live.ding.dingsdk.utils.Hook.BeforeRequestContextImpl;
import live.ding.dingsdk.utils.Utils; 

/**
 * Retrieve up-to-date metadata about a specific phone number
 */
public class Lookup implements
            MethodCallLookup {

    private final SDKConfiguration sdkConfiguration;

    Lookup(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }


    /**
     * Look up for phone number
     * @return The call builder
     */
    public LookupRequestBuilder lookup() {
        return new LookupRequestBuilder(this);
    }

    /**
     * Look up for phone number
     * @param customerUuid
     * @param phoneNumber
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public LookupResponse lookup(
            String customerUuid,
            String phoneNumber) throws Exception {
        return lookup(customerUuid, phoneNumber, Optional.empty());
    }
    
    /**
     * Look up for phone number
     * @param customerUuid
     * @param phoneNumber
     * @param type
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public LookupResponse lookup(
            String customerUuid,
            String phoneNumber,
            Optional<? extends List<Type>> type) throws Exception {
        LookupRequest request =
            LookupRequest
                .builder()
                .customerUuid(customerUuid)
                .phoneNumber(phoneNumber)
                .type(type)
                .build();
        
        String _baseUrl = this.sdkConfiguration.serverUrl;
        String _url = Utils.generateURL(
                LookupRequest.class,
                _baseUrl,
                "/lookup/{phone_number}",
                request, null);
        
        HTTPRequest _req = new HTTPRequest(_url, "GET");
        _req.addHeader("Accept", "application/json")
            .addHeader("user-agent", 
                SDKConfiguration.USER_AGENT);

        _req.addQueryParams(Utils.getQueryParams(
                LookupRequest.class,
                request, 
                null));
        _req.addHeaders(Utils.getHeadersFromMetadata(request, null));
        
        Optional<SecuritySource> _hookSecuritySource = this.sdkConfiguration.securitySource();
        Utils.configureSecurity(_req,  
                this.sdkConfiguration.securitySource.getSecurity());
        HTTPClient _client = this.sdkConfiguration.defaultClient;
        HttpRequest _r = 
            sdkConfiguration.hooks()
               .beforeRequest(
                  new BeforeRequestContextImpl(
                      "lookup", 
                      Optional.of(List.of()), 
                      _hookSecuritySource),
                  _req.build());
        HttpResponse<InputStream> _httpRes;
        try {
            _httpRes = _client.send(_r);
            if (Utils.statusCodeMatches(_httpRes.statusCode(), "400", "4XX", "5XX")) {
                _httpRes = sdkConfiguration.hooks()
                    .afterError(
                        new AfterErrorContextImpl(
                            "lookup",
                            Optional.of(List.of()),
                            _hookSecuritySource),
                        Optional.of(_httpRes),
                        Optional.empty());
            } else {
                _httpRes = sdkConfiguration.hooks()
                    .afterSuccess(
                        new AfterSuccessContextImpl(
                            "lookup",
                            Optional.of(List.of()), 
                            _hookSecuritySource),
                         _httpRes);
            }
        } catch (Exception _e) {
            _httpRes = sdkConfiguration.hooks()
                    .afterError(
                        new AfterErrorContextImpl(
                            "lookup",
                            Optional.of(List.of()),
                            _hookSecuritySource), 
                        Optional.empty(),
                        Optional.of(_e));
        }
        String _contentType = _httpRes
            .headers()
            .firstValue("Content-Type")
            .orElse("application/octet-stream");
        LookupResponse.Builder _resBuilder = 
            LookupResponse
                .builder()
                .contentType(_contentType)
                .statusCode(_httpRes.statusCode())
                .rawResponse(_httpRes);

        LookupResponse _res = _resBuilder.build();
        
        if (Utils.statusCodeMatches(_httpRes.statusCode(), "200")) {
            if (Utils.contentTypeMatches(_contentType, "application/json")) {
                live.ding.dingsdk.models.shared.LookupResponse _out = Utils.mapper().readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<live.ding.dingsdk.models.shared.LookupResponse>() {});
                _res.withLookupResponse(Optional.ofNullable(_out));
                return _res;
            } else {
                throw new SDKError(
                    _httpRes, 
                    _httpRes.statusCode(), 
                    "Unexpected content-type received: " + _contentType, 
                    Utils.extractByteArrayFromBody(_httpRes));
            }
        }
        if (Utils.statusCodeMatches(_httpRes.statusCode(), "400")) {
            if (Utils.contentTypeMatches(_contentType, "application/json")) {
                ErrorResponse _out = Utils.mapper().readValue(
                    Utils.toUtf8AndClose(_httpRes.body()),
                    new TypeReference<ErrorResponse>() {});
                throw _out;
            } else {
                throw new SDKError(
                    _httpRes, 
                    _httpRes.statusCode(), 
                    "Unexpected content-type received: " + _contentType, 
                    Utils.extractByteArrayFromBody(_httpRes));
            }
        }
        if (Utils.statusCodeMatches(_httpRes.statusCode(), "4XX", "5XX")) {
            // no content 
            throw new SDKError(
                    _httpRes, 
                    _httpRes.statusCode(), 
                    "API error occurred", 
                    Utils.extractByteArrayFromBody(_httpRes));
        }
        throw new SDKError(
            _httpRes, 
            _httpRes.statusCode(), 
            "Unexpected status code received: " + _httpRes.statusCode(), 
            Utils.extractByteArrayFromBody(_httpRes));
    }

}
