/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk;

import java.lang.String;
import java.util.Optional;
import live.ding.dingSdk.utils.HTTPClient;
import live.ding.dingSdk.utils.Hooks;
import live.ding.dingSdk.utils.RetryConfig;

class SDKConfiguration {
    public SecuritySource securitySource;
    
    public Optional<SecuritySource> securitySource() {
        return Optional.ofNullable(securitySource);
    }
    public HTTPClient defaultClient;
    public String serverUrl;
    public int serverIdx = 0;
    public String language = "java";
    public String openapiDocVersion = "1.0.0";
    public String sdkVersion = "0.6.0";
    public String genVersion = "2.399.0";
    public String userAgent = "speakeasy-sdk/java 0.6.0 2.399.0 1.0.0 live.ding.dingSdk";

    private Hooks _hooks = createHooks();

    private static Hooks createHooks() {
        Hooks hooks = new Hooks();
        return hooks;
    }
    
    public Hooks hooks() {
        return _hooks;
    }

    public void setHooks(Hooks hooks) {
        this._hooks = hooks;
    }

    /** 
     * Initializes state (for example hooks).
     **/
    public void initialize() {

    }

    
    
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
