/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package live.ding.dingSdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import live.ding.dingSdk.utils.SpeakeasyMetadata;


public class LookupRequest {
    @SpeakeasyMetadata("header:style=simple,explode=false,name=customer-uuid")
    public String customerUuid;

    public LookupRequest withCustomerUuid(String customerUuid) {
        this.customerUuid = customerUuid;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public live.ding.dingSdk.models.shared.LookupRequest lookupRequest;

    public LookupRequest withLookupRequest(live.ding.dingSdk.models.shared.LookupRequest lookupRequest) {
        this.lookupRequest = lookupRequest;
        return this;
    }
    
    public LookupRequest(@JsonProperty("customer-uuid") String customerUuid) {
        this.customerUuid = customerUuid;
  }
}
