/* 
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import live.ding.dingSdk.utils.SpeakeasyMetadata;


public class LookupRequest {
    @SpeakeasyMetadata("header:style=simple,explode=false,name=customer-uuid")
    public String customerUuid;

    public LookupRequest withCustomerUuid(String customerUuid) {
        this.customerUuid = customerUuid;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=phone_number")
    public String phoneNumber;

    public LookupRequest withPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }
    
    public LookupRequest(@JsonProperty("customer-uuid") String customerUuid, @JsonProperty("phone_number") String phoneNumber) {
        this.customerUuid = customerUuid;
        this.phoneNumber = phoneNumber;
  }
}
