/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import live.ding.dingSdk.models.shared.CreateCheckResponse;
import live.ding.dingSdk.utils.Response;
import live.ding.dingSdk.utils.Utils;


public class CheckResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * OK
     */
    private Optional<? extends CreateCheckResponse> createCheckResponse;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public CheckResponse(
            String contentType,
            Optional<? extends CreateCheckResponse> createCheckResponse,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(createCheckResponse, "createCheckResponse");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.createCheckResponse = createCheckResponse;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public CheckResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CreateCheckResponse> createCheckResponse() {
        return (Optional<CreateCheckResponse>) createCheckResponse;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public CheckResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * OK
     */
    public CheckResponse withCreateCheckResponse(CreateCheckResponse createCheckResponse) {
        Utils.checkNotNull(createCheckResponse, "createCheckResponse");
        this.createCheckResponse = Optional.ofNullable(createCheckResponse);
        return this;
    }

    /**
     * OK
     */
    public CheckResponse withCreateCheckResponse(Optional<? extends CreateCheckResponse> createCheckResponse) {
        Utils.checkNotNull(createCheckResponse, "createCheckResponse");
        this.createCheckResponse = createCheckResponse;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CheckResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CheckResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CheckResponse other = (CheckResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.createCheckResponse, other.createCheckResponse) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            createCheckResponse,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CheckResponse.class,
                "contentType", contentType,
                "createCheckResponse", createCheckResponse,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends CreateCheckResponse> createCheckResponse = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * OK
         */
        public Builder createCheckResponse(CreateCheckResponse createCheckResponse) {
            Utils.checkNotNull(createCheckResponse, "createCheckResponse");
            this.createCheckResponse = Optional.ofNullable(createCheckResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder createCheckResponse(Optional<? extends CreateCheckResponse> createCheckResponse) {
            Utils.checkNotNull(createCheckResponse, "createCheckResponse");
            this.createCheckResponse = createCheckResponse;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public CheckResponse build() {
            return new CheckResponse(
                contentType,
                createCheckResponse,
                statusCode,
                rawResponse);
        }
    }
}

