/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import live.ding.dingSdk.utils.Response;
import live.ding.dingSdk.utils.Utils;


public class CreateAuthenticationResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * OK
     */
    private Optional<? extends live.ding.dingSdk.models.shared.CreateAuthenticationResponse> createAuthenticationResponse;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public CreateAuthenticationResponse(
            String contentType,
            Optional<? extends live.ding.dingSdk.models.shared.CreateAuthenticationResponse> createAuthenticationResponse,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(createAuthenticationResponse, "createAuthenticationResponse");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.createAuthenticationResponse = createAuthenticationResponse;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public CreateAuthenticationResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<live.ding.dingSdk.models.shared.CreateAuthenticationResponse> createAuthenticationResponse() {
        return (Optional<live.ding.dingSdk.models.shared.CreateAuthenticationResponse>) createAuthenticationResponse;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public CreateAuthenticationResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * OK
     */
    public CreateAuthenticationResponse withCreateAuthenticationResponse(live.ding.dingSdk.models.shared.CreateAuthenticationResponse createAuthenticationResponse) {
        Utils.checkNotNull(createAuthenticationResponse, "createAuthenticationResponse");
        this.createAuthenticationResponse = Optional.ofNullable(createAuthenticationResponse);
        return this;
    }

    /**
     * OK
     */
    public CreateAuthenticationResponse withCreateAuthenticationResponse(Optional<? extends live.ding.dingSdk.models.shared.CreateAuthenticationResponse> createAuthenticationResponse) {
        Utils.checkNotNull(createAuthenticationResponse, "createAuthenticationResponse");
        this.createAuthenticationResponse = createAuthenticationResponse;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateAuthenticationResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateAuthenticationResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateAuthenticationResponse other = (CreateAuthenticationResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.createAuthenticationResponse, other.createAuthenticationResponse) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            createAuthenticationResponse,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateAuthenticationResponse.class,
                "contentType", contentType,
                "createAuthenticationResponse", createAuthenticationResponse,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends live.ding.dingSdk.models.shared.CreateAuthenticationResponse> createAuthenticationResponse = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * OK
         */
        public Builder createAuthenticationResponse(live.ding.dingSdk.models.shared.CreateAuthenticationResponse createAuthenticationResponse) {
            Utils.checkNotNull(createAuthenticationResponse, "createAuthenticationResponse");
            this.createAuthenticationResponse = Optional.ofNullable(createAuthenticationResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder createAuthenticationResponse(Optional<? extends live.ding.dingSdk.models.shared.CreateAuthenticationResponse> createAuthenticationResponse) {
            Utils.checkNotNull(createAuthenticationResponse, "createAuthenticationResponse");
            this.createAuthenticationResponse = createAuthenticationResponse;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public CreateAuthenticationResponse build() {
            return new CreateAuthenticationResponse(
                contentType,
                createAuthenticationResponse,
                statusCode,
                rawResponse);
        }
    }
}

