/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import live.ding.dingsdk.models.shared.AuthenticationStatusResponse;
import live.ding.dingsdk.models.shared.ErrorResponse;
import live.ding.dingsdk.utils.Response;
import live.ding.dingsdk.utils.Utils;


public class GetAuthenticationStatusResponse implements Response {

    /**
     * OK
     */
    private Optional<? extends AuthenticationStatusResponse> authenticationStatusResponse;

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * Bad Request
     */
    private Optional<? extends ErrorResponse> errorResponse;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public GetAuthenticationStatusResponse(
            Optional<? extends AuthenticationStatusResponse> authenticationStatusResponse,
            String contentType,
            Optional<? extends ErrorResponse> errorResponse,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(authenticationStatusResponse, "authenticationStatusResponse");
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(errorResponse, "errorResponse");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.authenticationStatusResponse = authenticationStatusResponse;
        this.contentType = contentType;
        this.errorResponse = errorResponse;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public GetAuthenticationStatusResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(Optional.empty(), contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AuthenticationStatusResponse> authenticationStatusResponse() {
        return (Optional<AuthenticationStatusResponse>) authenticationStatusResponse;
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * Bad Request
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ErrorResponse> errorResponse() {
        return (Optional<ErrorResponse>) errorResponse;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * OK
     */
    public GetAuthenticationStatusResponse withAuthenticationStatusResponse(AuthenticationStatusResponse authenticationStatusResponse) {
        Utils.checkNotNull(authenticationStatusResponse, "authenticationStatusResponse");
        this.authenticationStatusResponse = Optional.ofNullable(authenticationStatusResponse);
        return this;
    }

    /**
     * OK
     */
    public GetAuthenticationStatusResponse withAuthenticationStatusResponse(Optional<? extends AuthenticationStatusResponse> authenticationStatusResponse) {
        Utils.checkNotNull(authenticationStatusResponse, "authenticationStatusResponse");
        this.authenticationStatusResponse = authenticationStatusResponse;
        return this;
    }

    /**
     * HTTP response content type for this operation
     */
    public GetAuthenticationStatusResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * Bad Request
     */
    public GetAuthenticationStatusResponse withErrorResponse(ErrorResponse errorResponse) {
        Utils.checkNotNull(errorResponse, "errorResponse");
        this.errorResponse = Optional.ofNullable(errorResponse);
        return this;
    }

    /**
     * Bad Request
     */
    public GetAuthenticationStatusResponse withErrorResponse(Optional<? extends ErrorResponse> errorResponse) {
        Utils.checkNotNull(errorResponse, "errorResponse");
        this.errorResponse = errorResponse;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetAuthenticationStatusResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetAuthenticationStatusResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAuthenticationStatusResponse other = (GetAuthenticationStatusResponse) o;
        return 
            Objects.deepEquals(this.authenticationStatusResponse, other.authenticationStatusResponse) &&
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.errorResponse, other.errorResponse) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            authenticationStatusResponse,
            contentType,
            errorResponse,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAuthenticationStatusResponse.class,
                "authenticationStatusResponse", authenticationStatusResponse,
                "contentType", contentType,
                "errorResponse", errorResponse,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private Optional<? extends AuthenticationStatusResponse> authenticationStatusResponse = Optional.empty();
 
        private String contentType;
 
        private Optional<? extends ErrorResponse> errorResponse = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * OK
         */
        public Builder authenticationStatusResponse(AuthenticationStatusResponse authenticationStatusResponse) {
            Utils.checkNotNull(authenticationStatusResponse, "authenticationStatusResponse");
            this.authenticationStatusResponse = Optional.ofNullable(authenticationStatusResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder authenticationStatusResponse(Optional<? extends AuthenticationStatusResponse> authenticationStatusResponse) {
            Utils.checkNotNull(authenticationStatusResponse, "authenticationStatusResponse");
            this.authenticationStatusResponse = authenticationStatusResponse;
            return this;
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * Bad Request
         */
        public Builder errorResponse(ErrorResponse errorResponse) {
            Utils.checkNotNull(errorResponse, "errorResponse");
            this.errorResponse = Optional.ofNullable(errorResponse);
            return this;
        }

        /**
         * Bad Request
         */
        public Builder errorResponse(Optional<? extends ErrorResponse> errorResponse) {
            Utils.checkNotNull(errorResponse, "errorResponse");
            this.errorResponse = errorResponse;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public GetAuthenticationStatusResponse build() {
            return new GetAuthenticationStatusResponse(
                authenticationStatusResponse,
                contentType,
                errorResponse,
                statusCode,
                rawResponse);
        }
    }
}

