/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import live.ding.dingsdk.utils.SpeakeasyMetadata;
import live.ding.dingsdk.utils.Utils;


public class GetAuthenticationStatusRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=auth_uuid")
    private String authUuid;

    @JsonCreator
    public GetAuthenticationStatusRequest(
            String authUuid) {
        Utils.checkNotNull(authUuid, "authUuid");
        this.authUuid = authUuid;
    }

    @JsonIgnore
    public String authUuid() {
        return authUuid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GetAuthenticationStatusRequest withAuthUuid(String authUuid) {
        Utils.checkNotNull(authUuid, "authUuid");
        this.authUuid = authUuid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAuthenticationStatusRequest other = (GetAuthenticationStatusRequest) o;
        return 
            Objects.deepEquals(this.authUuid, other.authUuid);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            authUuid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAuthenticationStatusRequest.class,
                "authUuid", authUuid);
    }
    
    public final static class Builder {
 
        private String authUuid;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder authUuid(String authUuid) {
            Utils.checkNotNull(authUuid, "authUuid");
            this.authUuid = authUuid;
            return this;
        }
        
        public GetAuthenticationStatusRequest build() {
            return new GetAuthenticationStatusRequest(
                authUuid);
        }
    }
}

