/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.operations;

import java.lang.String;
import live.ding.dingSdk.utils.Utils;

public class GetAuthenticationStatusRequestBuilder {

    private String authUuid;
    private final SDKMethodInterfaces.MethodCallGetAuthenticationStatus sdk;

    public GetAuthenticationStatusRequestBuilder(SDKMethodInterfaces.MethodCallGetAuthenticationStatus sdk) {
        this.sdk = sdk;
    }

    public GetAuthenticationStatusRequestBuilder authUuid(String authUuid) {
        Utils.checkNotNull(authUuid, "authUuid");
        this.authUuid = authUuid;
        return this;
    }

    public GetAuthenticationStatusResponse call() throws Exception {

        return sdk.getAuthenticationStatus(
            authUuid);
    }
}
