/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import live.ding.dingsdk.utils.SpeakeasyMetadata;
import live.ding.dingsdk.utils.Utils;


public class LookupRequest {

    @SpeakeasyMetadata("header:style=simple,explode=false,name=customer-uuid")
    private String customerUuid;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=phone_number")
    private String phoneNumber;

    @JsonCreator
    public LookupRequest(
            String customerUuid,
            String phoneNumber) {
        Utils.checkNotNull(customerUuid, "customerUuid");
        Utils.checkNotNull(phoneNumber, "phoneNumber");
        this.customerUuid = customerUuid;
        this.phoneNumber = phoneNumber;
    }

    @JsonIgnore
    public String customerUuid() {
        return customerUuid;
    }

    @JsonIgnore
    public String phoneNumber() {
        return phoneNumber;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public LookupRequest withCustomerUuid(String customerUuid) {
        Utils.checkNotNull(customerUuid, "customerUuid");
        this.customerUuid = customerUuid;
        return this;
    }

    public LookupRequest withPhoneNumber(String phoneNumber) {
        Utils.checkNotNull(phoneNumber, "phoneNumber");
        this.phoneNumber = phoneNumber;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LookupRequest other = (LookupRequest) o;
        return 
            Objects.deepEquals(this.customerUuid, other.customerUuid) &&
            Objects.deepEquals(this.phoneNumber, other.phoneNumber);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            customerUuid,
            phoneNumber);
    }
    
    @Override
    public String toString() {
        return Utils.toString(LookupRequest.class,
                "customerUuid", customerUuid,
                "phoneNumber", phoneNumber);
    }
    
    public final static class Builder {
 
        private String customerUuid;
 
        private String phoneNumber;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder customerUuid(String customerUuid) {
            Utils.checkNotNull(customerUuid, "customerUuid");
            this.customerUuid = customerUuid;
            return this;
        }

        public Builder phoneNumber(String phoneNumber) {
            Utils.checkNotNull(phoneNumber, "phoneNumber");
            this.phoneNumber = phoneNumber;
            return this;
        }
        
        public LookupRequest build() {
            return new LookupRequest(
                customerUuid,
                phoneNumber);
        }
    }
}

