/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import live.ding.dingsdk.utils.SpeakeasyMetadata;
import live.ding.dingsdk.utils.Utils;


public class LookupRequest {

    @SpeakeasyMetadata("header:style=simple,explode=false,name=customer-uuid")
    private String customerUuid;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=phone_number")
    private String phoneNumber;

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")
    private Optional<? extends List<Type>> type;

    @JsonCreator
    public LookupRequest(
            String customerUuid,
            String phoneNumber,
            Optional<? extends List<Type>> type) {
        Utils.checkNotNull(customerUuid, "customerUuid");
        Utils.checkNotNull(phoneNumber, "phoneNumber");
        Utils.checkNotNull(type, "type");
        this.customerUuid = customerUuid;
        this.phoneNumber = phoneNumber;
        this.type = type;
    }
    
    public LookupRequest(
            String customerUuid,
            String phoneNumber) {
        this(customerUuid, phoneNumber, Optional.empty());
    }

    @JsonIgnore
    public String customerUuid() {
        return customerUuid;
    }

    @JsonIgnore
    public String phoneNumber() {
        return phoneNumber;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Type>> type() {
        return (Optional<List<Type>>) type;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public LookupRequest withCustomerUuid(String customerUuid) {
        Utils.checkNotNull(customerUuid, "customerUuid");
        this.customerUuid = customerUuid;
        return this;
    }

    public LookupRequest withPhoneNumber(String phoneNumber) {
        Utils.checkNotNull(phoneNumber, "phoneNumber");
        this.phoneNumber = phoneNumber;
        return this;
    }

    public LookupRequest withType(List<Type> type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }

    public LookupRequest withType(Optional<? extends List<Type>> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LookupRequest other = (LookupRequest) o;
        return 
            Objects.deepEquals(this.customerUuid, other.customerUuid) &&
            Objects.deepEquals(this.phoneNumber, other.phoneNumber) &&
            Objects.deepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            customerUuid,
            phoneNumber,
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(LookupRequest.class,
                "customerUuid", customerUuid,
                "phoneNumber", phoneNumber,
                "type", type);
    }
    
    public final static class Builder {
 
        private String customerUuid;
 
        private String phoneNumber;
 
        private Optional<? extends List<Type>> type = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder customerUuid(String customerUuid) {
            Utils.checkNotNull(customerUuid, "customerUuid");
            this.customerUuid = customerUuid;
            return this;
        }

        public Builder phoneNumber(String phoneNumber) {
            Utils.checkNotNull(phoneNumber, "phoneNumber");
            this.phoneNumber = phoneNumber;
            return this;
        }

        public Builder type(List<Type> type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Builder type(Optional<? extends List<Type>> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }
        
        public LookupRequest build() {
            return new LookupRequest(
                customerUuid,
                phoneNumber,
                type);
        }
    }
}

