/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingsdk.models.operations;

import java.util.Optional;
import live.ding.dingsdk.models.shared.RetryAuthenticationRequest;
import live.ding.dingsdk.utils.Utils;

public class RetryRequestBuilder {

    private Optional<? extends RetryAuthenticationRequest> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallRetry sdk;

    public RetryRequestBuilder(SDKMethodInterfaces.MethodCallRetry sdk) {
        this.sdk = sdk;
    }
                
    public RetryRequestBuilder request(RetryAuthenticationRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public RetryRequestBuilder request(Optional<? extends RetryAuthenticationRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RetryResponse call() throws Exception {

        return sdk.retry(
            request);
    }
}
