/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;
import live.ding.dingSdk.models.shared.RetryAuthenticationResponse;
import live.ding.dingSdk.utils.Response;
import live.ding.dingSdk.utils.Utils;


public class RetryResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * OK
     */
    private Optional<? extends RetryAuthenticationResponse> retryAuthenticationResponse;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public RetryResponse(
            String contentType,
            Optional<? extends RetryAuthenticationResponse> retryAuthenticationResponse,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(retryAuthenticationResponse, "retryAuthenticationResponse");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.retryAuthenticationResponse = retryAuthenticationResponse;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public RetryResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<RetryAuthenticationResponse> retryAuthenticationResponse() {
        return (Optional<RetryAuthenticationResponse>) retryAuthenticationResponse;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public RetryResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * OK
     */
    public RetryResponse withRetryAuthenticationResponse(RetryAuthenticationResponse retryAuthenticationResponse) {
        Utils.checkNotNull(retryAuthenticationResponse, "retryAuthenticationResponse");
        this.retryAuthenticationResponse = Optional.ofNullable(retryAuthenticationResponse);
        return this;
    }

    /**
     * OK
     */
    public RetryResponse withRetryAuthenticationResponse(Optional<? extends RetryAuthenticationResponse> retryAuthenticationResponse) {
        Utils.checkNotNull(retryAuthenticationResponse, "retryAuthenticationResponse");
        this.retryAuthenticationResponse = retryAuthenticationResponse;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public RetryResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public RetryResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RetryResponse other = (RetryResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.retryAuthenticationResponse, other.retryAuthenticationResponse) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            retryAuthenticationResponse,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RetryResponse.class,
                "contentType", contentType,
                "retryAuthenticationResponse", retryAuthenticationResponse,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends RetryAuthenticationResponse> retryAuthenticationResponse = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * OK
         */
        public Builder retryAuthenticationResponse(RetryAuthenticationResponse retryAuthenticationResponse) {
            Utils.checkNotNull(retryAuthenticationResponse, "retryAuthenticationResponse");
            this.retryAuthenticationResponse = Optional.ofNullable(retryAuthenticationResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder retryAuthenticationResponse(Optional<? extends RetryAuthenticationResponse> retryAuthenticationResponse) {
            Utils.checkNotNull(retryAuthenticationResponse, "retryAuthenticationResponse");
            this.retryAuthenticationResponse = retryAuthenticationResponse;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public RetryResponse build() {
            return new RetryResponse(
                contentType,
                retryAuthenticationResponse,
                statusCode,
                rawResponse);
        }
    }
}

