/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateCheckResponseStatus - A status representing the result of the check.
 */
public enum CreateCheckResponseStatus {
    VALID("valid"),
    INVALID("invalid"),
    WITHOUT_ATTEMPT("without_attempt"),
    RATE_LIMITED("rate_limited"),
    ALREADY_VALIDATED("already_validated"),
    EXPIRED_AUTH("expired_auth");

    @JsonValue
    public final String value;

    private CreateCheckResponseStatus(String value) {
        this.value = value;
    }
}
