/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateCheckResponse {
    /**
     * The UUID of the corresponding authentication.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authentication_uuid")
    public String authenticationUuid;

    public CreateCheckResponse withAuthenticationUuid(String authenticationUuid) {
        this.authenticationUuid = authenticationUuid;
        return this;
    }
    
    /**
     * A status representing the result of the check.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public CreateCheckResponseStatus status;

    public CreateCheckResponse withStatus(CreateCheckResponseStatus status) {
        this.status = status;
        return this;
    }
    
    public CreateCheckResponse(){}
}
