/* 
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateCheckRequest {
    /**
     * The authentication UUID that was returned when you created the authentication.
     */
    @JsonProperty("authentication_uuid")
    public String authenticationUuid;

    public CreateCheckRequest withAuthenticationUuid(String authenticationUuid) {
        this.authenticationUuid = authenticationUuid;
        return this;
    }
    
    /**
     * The code that the user entered.
     */
    @JsonProperty("check_code")
    public String checkCode;

    public CreateCheckRequest withCheckCode(String checkCode) {
        this.checkCode = checkCode;
        return this;
    }
    
    /**
     * Your customer UUID, which can be found in the API settings in the Dashboard.
     */
    @JsonProperty("customer_uuid")
    public String customerUuid;

    public CreateCheckRequest withCustomerUuid(String customerUuid) {
        this.customerUuid = customerUuid;
        return this;
    }
    
    public CreateCheckRequest(@JsonProperty("authentication_uuid") String authenticationUuid, @JsonProperty("check_code") String checkCode, @JsonProperty("customer_uuid") String customerUuid) {
        this.authenticationUuid = authenticationUuid;
        this.checkCode = checkCode;
        this.customerUuid = customerUuid;
  }
}
