/* 
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DeviceType - The type of device the user is using.
 */
public enum DeviceType {
    IOS("IOS"),
    ANDROID("ANDROID"),
    WEB("WEB");

    @JsonValue
    public final String value;

    private DeviceType(String value) {
        this.value = value;
    }
}
