/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ErrorResponse {
    /**
     * A machine-readable code that describes the error. Possible values are:
     *   * `invalid_phone_number` - This is not a valid E.164 number.
     *   * `internal_server_error` - An internal server error occurred.
     *   * `bad_request` - The request was malformed.
     *   * `account_invalid` - The customer UUID you provided is invalid.
     *   * `negative_balance` - You have a negative balance.
     *   * `invalid_line` - Ding does not support this type of phone number.
     *   * `unsupported_region` - Ding does not support this region yet.
     *   * `invalid_auth_uuid` - The authentication UUID you provided is invalid.
     *   * `blocked_number` - The phone number you provided is in the blocklist.
     *   * `invalid_app_version` - The app version you provided is invalid.
     *   * `invalid_os_version` - The OS version you provided is invalid.
     *   * `invalid_device_model` - The device model you provided is invalid.
     *   * `invalid_device_id` - The device ID you provided is invalid.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    public Code code;

    public ErrorResponse withCode(Code code) {
        this.code = code;
        return this;
    }
    
    /**
     * A link to the documentation that describes the error.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("doc_url")
    public String docUrl;

    public ErrorResponse withDocUrl(String docUrl) {
        this.docUrl = docUrl;
        return this;
    }
    
    /**
     * A human-readable message that describes the error.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public ErrorResponse withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public ErrorResponse(){}
}
