/* 
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class FeedbackRequest {
    /**
     * Your customer UUID, which can be found in the API settings in the dashboard.
     */
    @JsonProperty("customer_uuid")
    public String customerUuid;

    public FeedbackRequest withCustomerUuid(String customerUuid) {
        this.customerUuid = customerUuid;
        return this;
    }
    
    /**
     * An E.164 formatted phone number.
     */
    @JsonProperty("phone_number")
    public String phoneNumber;

    public FeedbackRequest withPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }
    
    /**
     * The type of the feedback.
     */
    @JsonProperty("status")
    public FeedbackRequestStatus status;

    public FeedbackRequest withStatus(FeedbackRequestStatus status) {
        this.status = status;
        return this;
    }
    
    public FeedbackRequest(@JsonProperty("customer_uuid") String customerUuid, @JsonProperty("phone_number") String phoneNumber, @JsonProperty("status") FeedbackRequestStatus status) {
        this.customerUuid = customerUuid;
        this.phoneNumber = phoneNumber;
        this.status = status;
  }
}
