/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class LookupResponse {
    /**
     * The carrier of the phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("carrier")
    public String carrier;

    public LookupResponse withCarrier(String carrier) {
        this.carrier = carrier;
        return this;
    }
    
    /**
     * The ISO 3166-1 alpha-2 country code of the phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country_code")
    public String countryCode;

    public LookupResponse withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    /**
     * The type of phone line.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_type")
    public LineType lineType;

    public LookupResponse withLineType(LineType lineType) {
        this.lineType = lineType;
        return this;
    }
    
    /**
     * The mobile country code of the phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mcc")
    public String mcc;

    public LookupResponse withMcc(String mcc) {
        this.mcc = mcc;
        return this;
    }
    
    /**
     * The mobile network code of the phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mnc")
    public String mnc;

    public LookupResponse withMnc(String mnc) {
        this.mnc = mnc;
        return this;
    }
    
    /**
     * Whether the phone number has been ported.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("number_ported")
    public Boolean numberPorted;

    public LookupResponse withNumberPorted(Boolean numberPorted) {
        this.numberPorted = numberPorted;
        return this;
    }
    
    /**
     * An E.164 formatted phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone_number")
    public String phoneNumber;

    public LookupResponse withPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }
    
    public LookupResponse(){}
}
