/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package live.ding.dingSdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Status - The status of the authentication.
 */
public enum Status {
    PENDING("pending"),
    RATE_LIMITED("rate_limited"),
    SPAM_DETECTED("spam_detected");

    @JsonValue
    public final String value;

    private Status(String value) {
        this.value = value;
    }
}
