workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
        registry:
            location: registry.speakeasyapi.dev/ding/ding/my-source
targets:
    live.ding.dingsdk:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: f1b6diLi
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ding/ding/my-source-java-code-samples
            blocking: false
