/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package live.ding.dingSdk;

import live.ding.dingSdk.utils.HTTPClient;
import live.ding.dingSdk.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public String server;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "0.2.0";
	public String genVersion = "2.230.1";
	public String userAgent = "speakeasy-sdk/java 0.2.0 2.230.1 1.0.0 live.ding.dingSdk";
	
	
}