/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package live.ding.dingsdk.utils;

public final class Constants {

    public static final boolean HAS_CLIENT_CREDENTIALS_BASIC = false;

}